// Postgres schema (Drizzle ORM). New to Porphyra — no upstream equivalent
// (the source project stores everything in flat markdown/TSV files; this is
// the from-scratch relational design described in the approved plan's "Data
// model" section).
//
// NOTE on the `user`/`session`/`account`/`verification`/`twoFactor` tables
// below: these mirror Better Auth's own default schema field-for-field
// (https://better-auth.com/docs/concepts/database,
// https://better-auth.com/docs/plugins/2fa#schema), hand-written rather
// than generated by `@better-auth/cli generate` — that CLI needs a live
// Postgres connection to introspect against, which isn't available in this
// environment. If Better Auth's schema requirements change (a version
// bump, a new plugin), regenerate with the CLI against a real DB and diff
// against this file rather than trusting this comment to have stayed
// current.

import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  twoFactorEnabled: boolean("two_factor_enabled").default(false), // added by the twoFactor plugin
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** One row per (user, auth method) — a credentials login and each linked
 * OAuth provider all get their own row here, all pointing at the same
 * `user`. `password` is Better Auth's OWN hash of the Argon2id verifier
 * described in apps/app/src/lib/auth.ts — never the user's real password,
 * never the value that unlocks their vault. */
export const account = pgTable("account", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  idToken: text("id_token"),
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Email verification tokens, password-reset tokens, etc. — short-lived,
 * `identifier` is typically the email + purpose, `value` the token itself. */
export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** TOTP secret + backup codes, added by the twoFactor plugin. `secret` and
 * `backupCodes` are Better Auth's own encrypted-at-rest values (its own
 * mechanism, unrelated to the vault's E2EE) — not touched by
 * @porphyra/crypto. `failedVerificationCount`/`lockedUntil` implement
 * account lockout against TOTP brute-forcing. */
export const twoFactor = pgTable("two_factor", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  secret: text("secret").notNull(),
  backupCodes: text("backup_codes").notNull(),
  verified: boolean("verified").notNull().default(false),
  failedVerificationCount: integer("failed_verification_count").notNull().default(0),
  lockedUntil: timestamp("locked_until", { withTimezone: true }),
});

/**
 * Admin allowlist for /admin/* routes. A separate table, not an
 * `isAdmin` column on `user` — that table intentionally mirrors Better
 * Auth's own schema field-for-field (see its doc comment above); adding an
 * app-specific field there breaks that invariant for one boolean's worth of
 * convenience. Presence of a row IS admin status — no `role` enum, because
 * there is exactly one privilege tier right now.
 */
export const admins = pgTable("admins", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Pre-launch waitlist (Phase 1, apps/web's marketing site). Deliberately NOT
 * linked to `user` — a waitlist signup precedes account
 * creation and most rows will never become a user. Email is stored in clear
 * (not vault content — no encryption story applies before there's an
 * account or a DEK to encrypt it with).
 */
export const waitlistEntries = pgTable(
  "waitlist_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").notNull().unique(),
    consentedAt: timestamp("consented_at", { withTimezone: true }).notNull(),
    source: text("source"), // e.g. "marketing_home", "for_designers" — which page/segment
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("waitlist_entries_created_idx").on(table.createdAt)],
);

export const applicationStateEnum = pgEnum("application_state", [
  "evaluated",
  "applied",
  "responded",
  "interview",
  "offer",
  "rejected",
  "discarded",
  "skip",
  "hired",
]);

export const vaultItemTypeEnum = pgEnum("vault_item_type", [
  "cv",
  "report",
  "cover_letter",
  "interview_note",
  "contact",
  "jd",
  "provider_key",
]);

export const planTierEnum = pgEnum("plan_tier", ["free", "pro"]);

/**
 * Per-user key material. Only WRAPPED keys ever touch the server — see the
 * plan's Encryption design § Key hierarchy. `wrappedDek` and
 * `recoveryWrappedDek` are ciphertext; the server cannot unwrap either.
 */
export const userKeys = pgTable("user_keys", {
  id: uuid("id").primaryKey().defaultRandom(),
  // One key hierarchy per user — key rotation UPDATES this row (bumping
  // keyVersion), it never inserts a second one. `.unique()` makes that a DB
  // invariant, not just a convention the app has to remember to honor.
  userId: text("user_id")
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: "cascade" }),
  // Each wrapped key is an AES-GCM {ciphertext, iv} pair (see
  // packages/crypto's EncryptedPayload) — stored as two columns rather than
  // one JSON blob so `iv` can never accidentally be reused as a value
  // elsewhere; both are base64.
  wrappedDekCiphertext: text("wrapped_dek_ciphertext").notNull(),
  wrappedDekIv: text("wrapped_dek_iv").notNull(),
  encSalt: text("enc_salt").notNull(), // Argon2id salt for the Master Key, base64
  recoveryWrappedDekCiphertext: text("recovery_wrapped_dek_ciphertext").notNull(),
  recoveryWrappedDekIv: text("recovery_wrapped_dek_iv").notNull(),
  kdfParams: jsonb("kdf_params").notNull(), // KdfParams from packages/crypto — { algo, memoryKb, iterations, parallelism, hashLengthBytes }
  keyVersion: integer("key_version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  rotatedAt: timestamp("rotated_at", { withTimezone: true }),
});

/**
 * Encrypted content — CV, reports, cover letters, notes, contacts, raw JD
 * text, and any provider key the user brings themselves. `blindIndex` is an
 * HMAC over a normalized plaintext field (e.g. company name) so the server
 * can filter/dedupe without learning the value — see the plan's "Encrypted
 * vs. clear" split.
 */
export const vaultItems = pgTable(
  "vault_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    type: vaultItemTypeEnum("type").notNull(),
    ciphertext: text("ciphertext").notNull(), // base64
    iv: text("iv").notNull(), // base64, unique per record
    blindIndex: text("blind_index"), // nullable — not every item type needs one
    applicationId: uuid("application_id"), // FK added once `applications` exists below
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("vault_items_user_idx").on(table.userId),
    index("vault_items_blind_index_idx").on(table.blindIndex),
  ],
);

/**
 * Application tracker. Metadata stays CLEAR (drives the funnel/analytics
 * queries directly); the report/notes/JD content lives encrypted in
 * `vault_items` and is linked, not embedded.
 *
 * Company/role appear TWICE, deliberately: the blind index is a one-way
 * hash for server-side filtering/dedup (the server can test "does this
 * match" but never recover the value — see packages/crypto's blindIndex.ts)
 * and is useless for rendering a pipeline list. The `*Ciphertext`/`*Iv`
 * pair is genuinely encrypted (reversible, client-side only) so the UI has
 * something to actually decrypt and show the user.
 */
export const applications = pgTable(
  "applications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    companyBlindIndex: text("company_blind_index").notNull(),
    roleBlindIndex: text("role_blind_index").notNull(),
    companyCiphertext: text("company_ciphertext").notNull(),
    companyIv: text("company_iv").notNull(),
    roleCiphertext: text("role_ciphertext").notNull(),
    roleIv: text("role_iv").notNull(),
    /** FK to the vault_items row holding the full encrypted evaluation
     * report — set once evaluation completes. */
    reportItemId: uuid("report_item_id"),
    state: applicationStateEnum("state").notNull().default("evaluated"),
    score: numeric("score", { precision: 3, scale: 2 }), // 0.00–5.00
    legitimacyTier: text("legitimacy_tier"),
    atsVendor: text("ats_vendor"), // greenhouse | lever | ashby | workday | ... — clear, not sensitive
    sourcePortal: text("source_portal"),
    appliedAt: timestamp("applied_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("applications_user_idx").on(table.userId),
    index("applications_state_idx").on(table.state),
  ],
);

export const subscriptions = pgTable("subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: "cascade" }),
  stripeCustomerId: text("stripe_customer_id").notNull(),
  stripeSubscriptionId: text("stripe_subscription_id"),
  tier: planTierEnum("tier").notNull().default("free"),
  status: text("status").notNull().default("active"), // mirrors Stripe's subscription.status
  currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
  cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Webhook idempotency ledger. Stripe explicitly does not guarantee
 * exactly-once delivery — the same event can arrive twice (a retry after a
 * slow 200, a network blip). `id` is Stripe's own event ID, so a second
 * delivery of the same event fails the primary-key insert and the webhook
 * handler treats that as "already processed", not an error.
 */
export const processedStripeEvents = pgTable("processed_stripe_events", {
  id: text("id").primaryKey(), // Stripe event ID, e.g. "evt_..."
  type: text("type").notNull(),
  processedAt: timestamp("processed_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Monthly rolling usage against the plan's AI-evaluation quota.
 *
 * `(userId, periodStart)` is UNIQUE, not just indexed — this is what makes
 * `tryConsumeEvaluationQuota` (apps/app/src/lib/quota.ts) a single atomic
 * `INSERT ... ON CONFLICT (user_id, period_start) DO UPDATE ... WHERE`
 * instead of a read-then-write race. Without the uniqueness constraint,
 * `ON CONFLICT` has no target and Postgres rejects the statement outright —
 * this isn't just an optimization, the atomic quota check depends on it.
 */
export const usageCounters = pgTable(
  "usage_counters",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    periodStart: timestamp("period_start", { withTimezone: true }).notNull(),
    evaluationsUsed: integer("evaluations_used").notNull().default(0),
    aiCostUsd: numeric("ai_cost_usd", { precision: 10, scale: 4 }).notNull().default("0"),
  },
  (table) => [uniqueIndex("usage_counters_user_period_idx").on(table.userId, table.periodStart)],
);

/**
 * Behavioural analytics only — see the plan's E2EE-vs-analytics resolution.
 * `props` must never contain vault content; enforced in the event-emission
 * helper (Phase 5), not just by convention here.
 */
export const events = pgTable(
  "events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
    sessionId: text("session_id"),
    name: text("name").notNull(), // e.g. "evaluation_started", "checkout_completed"
    props: jsonb("props").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("events_name_idx").on(table.name), index("events_user_idx").on(table.userId)],
);

/** Append-only. Nothing ever updates or deletes a row here except the
 * account-deletion retention job, and that's logged in its own row first. */
export const auditLog = pgTable("audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
  action: text("action").notNull(), // "login", "password_change", "key_rotation", "export", ...
  ip: text("ip"),
  userAgent: text("user_agent"),
  metadata: jsonb("metadata").notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const aiJobStatusEnum = pgEnum("ai_job_status", [
  "queued",
  "processing",
  "completed",
  "failed",
]);

/** Queue state for the consented AI evaluation path. `costUsd` feeds
 * `usage_counters` and the admin cost dashboard (Phase 5). Payloads are
 * NEVER persisted here — only token counts and cost, after the fact. */
export const aiJobs = pgTable(
  "ai_jobs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    status: aiJobStatusEnum("status").notNull().default("queued"),
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    costUsd: numeric("cost_usd", { precision: 10, scale: 6 }),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [
    index("ai_jobs_user_idx").on(table.userId),
    index("ai_jobs_status_idx").on(table.status),
  ],
);
